<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="FluentResults" />
        <PackageReference Include="LanguageExt.Core" />
        <PackageReference Include="MassTransit" />
        <PackageReference Include="MediatR" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="Bogus">
        <HintPath>..\..\..\..\..\..\..\Users\anton\.nuget\packages\bogus\35.6.1\lib\net6.0\Bogus.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>