<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Bogus" />
        <PackageReference Include="FluentResults" />
        <PackageReference Include="JsonNet.ContractResolvers" />
        <PackageReference Include="LanguageExt.Core" />
        <PackageReference Include="MassTransit" />
        <PackageReference Include="MediatR" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>
</Project>